name: hr-attrition-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipywidgets
  - widgetsnbextension
  - jupyterlab_widgets
  - scipy
  - statsmodels
  - voila
  - traitlets
  - pip
  - pip:
      - requests
